# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.udo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1c7f5e5b48215afd0eeeb16b37e4f418eea5665515a640362d70177d063db67a_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.udo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1c7f5e5b48215afd0eeeb16b37e4f418eea5665515a640362d70177d063db67a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.udo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.udo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8de4c9ca90d7182f666f010f9cebe1ad7d7b8e5cda338578f9ae9f9a9fe356a9_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.udo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8de4c9ca90d7182f666f010f9cebe1ad7d7b8e5cda338578f9ae9f9a9fe356a9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.udo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2

  orderer.udo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.udo.com
    container_name: orderer.udo.com

  peer0.org1.udo.com:
    container_name: peer0.org1.udo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.udo.com

  peer1.org1.udo.com:
    container_name: peer1.org1.udo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.udo.com

  peer0.org2.udo.com:
    container_name: peer0.org2.udo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.udo.com

  peer1.org2.udo.com:
    container_name: peer1.org2.udo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.udo.com
