#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  orderer.udo.com:
    container_name: orderer.udo.com
    image: hyperledger/udo-orderer
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerOrg1/tls/ca.crt, /etc/hyperledger/crypto/peerOrg2/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/udo/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel/channel-artifacts:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/udo.com/orderers/orderer.udo.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/org1.udo.com/peers/peer0.org1.udo.com/:/etc/hyperledger/crypto/peerOrg1
        - ./channel/crypto-config/peerOrganizations/org2.udo.com/peers/peer0.org2.udo.com/:/etc/hyperledger/crypto/peerOrg2

  peer0.org1.udo.com:
    container_name: peer0.org1.udo.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.udo.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.udo.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.udo.com/peers/peer0.org1.udo.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.udo.com


  peer1.org1.udo.com:
    container_name: peer1.org1.udo.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.udo.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.udo.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.udo.com/peers/peer1.org1.udo.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.udo.com
      
  peer0.org2.udo.com:
    container_name: peer0.org2.udo.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.udo.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.udo.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.udo.com/peers/peer0.org2.udo.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.udo.com

  peer1.org2.udo.com:
    container_name: peer1.org2.udo.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.udo.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.udo.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.udo.com/peers/peer1.org2.udo.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.udo.com

  cli:
      container_name: cli
      image: hyperledger/udo-tools
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - GODEBUG=netdns=go
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_LOGGING_LEVEL=DEBUG
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.org1.udo.com:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/udo/peer/crypto/peerOrganizations/org1.udo.com/peers/peer0.org1.udo.com/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/udo/peer/crypto/peerOrganizations/org1.udo.com/peers/peer0.org1.udo.com/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/udo/peer/crypto/peerOrganizations/org1.udo.com/peers/peer0.org1.udo.com/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/udo/peer/crypto/peerOrganizations/org1.udo.com/users/Admin@org1.udo.com/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/udo/peer
      command: /bin/bash
      volumes:
          - /var/run/:/host/var/run/
          - ./src/github.com/:/opt/gopath/src/github.com/hyperledger/udo/examples/chaincode/go
          - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/udo/peer/crypto/
      depends_on:
        - orderer.udo.com
        - peer0.org1.udo.com
        - peer1.org1.udo.com
        - peer0.org2.udo.com
        - peer1.org2.udo.com
